name: Deploy to DonWeb FTP using lftp

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build and export Next.js
        run: |
          npm run build
          npm run export

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy via FTP with lftp
        env:
          FTP_HOST: c2831423.ferozo.com
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: /public_html
        run: |
          lftp -c "
            open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
            mirror -R --delete --verbose ./out $FTP_REMOTE_DIR
            bye
          "
